export const projects = [
  {id: 101,
    name: 'Zentry Web Site',
    technologies:
      'React, Typescript, GSAP, Tailwind',
    http: 'https://zentry-gamma.vercel.app/',
    github: 'https://github.com/alexandrkadai/zentry',
    src: 'zentry.png',
  },
  {
    id: 0,
    name: 'Eccomerce Sheaker Shop',
    technologies:
      'Next.js, React, Redis, Typescript, Prisma, Zod, Conform, Recharts PostgresSql, Stripe, ShadCn,  Tailwind',
    http: 'https://ecommsneaker.vercel.app/',
    github: 'https://github.com/alexandrkadai/ecommsneaker',
    src: 'EcomSne.png',
  },
  {
    id: 1,
    name: 'School dashboard',
    technologies: 'Next.js, React, Typescript, Recharts, Zod, React-Hook-Form ShadCn,  Tailwind',
    http: 'https://schooldashboard-tau.vercel.app/',
    github: 'https://github.com/alexandrkadai/school',
    src: 'school.png',
  },
  {
    id: 2,
    name: 'RowdyIs online shop',
    technologies: 'React, Redux, Typescript, Framer Motion, Css modules',
    http: 'https://onlineshop-bice.vercel.app/',
    github: 'https://github.com/alexandrkadai/onlineshop',
    src: 'rowdy.png',
  },
  {
    id: 3,
    name: 'PonPon online shop',
    technologies: 'React, Redux Saga Thunk, Typescript, Stripe, Firebase, Css modules',
    http: 'https://incomparable-jalebi-5a29d8.netlify.app/',
    github: 'https://github.com/alexandrkadai/PonPon',
    src: 'ponpon.png',
  },
  {
    id: 4,
    name: 'AirBnb Clone React Native',
    technologies: 'React Native, Three.js, Typescript, Tailwind, Framer Motin, Email.js',
    http: 'expo.dev/@takeree',
    github: 'https://github.com/alexandrkadai/hotelsapp',
    src: 'airbnb.png',
  },
  {
    id: 5,
    name: 'Three.js Pet Project',
    technologies: 'React, Three.js, Tailwind, Framer Motin, Email.js',
    http: 'https://portfolio-lyart-xi-88.vercel.app/',
    github: 'https://github.com/alexandrkadai/portfolio',
    src: 'threejs.png',
  },
];
